// Common built-in functions per dialect, with short signatures for the suggest widget.
import type { Dialect } from '@shared/types'

export interface BuiltinFunction {
  name: string
  /** Argument list including parentheses, e.g. "(value, default)". */
  signature: string
  /** Short description shown in the details pane. */
  doc: string
  /** Return type, when meaningful. */
  returns?: string
}

const fn = (name: string, signature: string, doc: string, returns?: string): BuiltinFunction => ({ name, signature, doc, returns })

const POSTGRES_FUNCTIONS: BuiltinFunction[] = [
  // aggregates
  fn('count', '(expr | *)', 'Number of input rows (or non-null values).', 'bigint'),
  fn('sum', '(expr)', 'Sum of non-null input values.'),
  fn('avg', '(expr)', 'Average of non-null input values.', 'numeric'),
  fn('min', '(expr)', 'Minimum of input values.'),
  fn('max', '(expr)', 'Maximum of input values.'),
  fn('array_agg', '(expr [ORDER BY …])', 'Input values concatenated into an array.', 'anyarray'),
  fn('string_agg', '(expr, delimiter [ORDER BY …])', 'Input values concatenated, separated by delimiter.', 'text'),
  fn('json_agg', '(expr)', 'Input values aggregated as a JSON array.', 'json'),
  fn('jsonb_agg', '(expr)', 'Input values aggregated as a JSONB array.', 'jsonb'),
  fn('json_object_agg', '(key, value)', 'Key/value pairs aggregated into a JSON object.', 'json'),
  fn('jsonb_object_agg', '(key, value)', 'Key/value pairs aggregated into a JSONB object.', 'jsonb'),
  fn('bool_and', '(expr)', 'True if all input values are true.', 'boolean'),
  fn('bool_or', '(expr)', 'True if at least one input value is true.', 'boolean'),
  fn('every', '(expr)', 'Equivalent to bool_and.', 'boolean'),
  fn('stddev', '(expr)', 'Sample standard deviation.'),
  fn('variance', '(expr)', 'Sample variance.'),
  fn('percentile_cont', '(fraction) WITHIN GROUP (ORDER BY …)', 'Continuous percentile.'),
  fn('percentile_disc', '(fraction) WITHIN GROUP (ORDER BY …)', 'Discrete percentile.'),
  fn('mode', '() WITHIN GROUP (ORDER BY …)', 'Most frequent value.'),
  // window
  fn('row_number', '()', 'Number of the current row within its partition.', 'bigint'),
  fn('rank', '()', 'Rank of the current row with gaps.', 'bigint'),
  fn('dense_rank', '()', 'Rank of the current row without gaps.', 'bigint'),
  fn('percent_rank', '()', 'Relative rank of the current row.', 'double precision'),
  fn('cume_dist', '()', 'Cumulative distribution.', 'double precision'),
  fn('ntile', '(buckets)', 'Bucket number from 1 to buckets.', 'integer'),
  fn('lag', '(value [, offset [, default]])', 'Value of the row offset rows before the current row.'),
  fn('lead', '(value [, offset [, default]])', 'Value of the row offset rows after the current row.'),
  fn('first_value', '(value)', 'Value at the first row of the window frame.'),
  fn('last_value', '(value)', 'Value at the last row of the window frame.'),
  fn('nth_value', '(value, n)', 'Value at the n-th row of the window frame.'),
  // conditional
  fn('coalesce', '(value [, …])', 'First non-null argument.'),
  fn('nullif', '(value1, value2)', 'Null if value1 equals value2, else value1.'),
  fn('greatest', '(value [, …])', 'Largest argument.'),
  fn('least', '(value [, …])', 'Smallest argument.'),
  // strings
  fn('length', '(text)', 'Number of characters.', 'integer'),
  fn('char_length', '(text)', 'Number of characters.', 'integer'),
  fn('lower', '(text)', 'Convert to lower case.', 'text'),
  fn('upper', '(text)', 'Convert to upper case.', 'text'),
  fn('initcap', '(text)', 'First letter of each word upper case.', 'text'),
  fn('trim', '([LEADING | TRAILING | BOTH] [chars FROM] text)', 'Remove characters from the ends.', 'text'),
  fn('btrim', '(text [, chars])', 'Remove characters from both ends.', 'text'),
  fn('ltrim', '(text [, chars])', 'Remove leading characters.', 'text'),
  fn('rtrim', '(text [, chars])', 'Remove trailing characters.', 'text'),
  fn('substring', '(text [FROM start] [FOR count])', 'Extract a substring.', 'text'),
  fn('substr', '(text, start [, count])', 'Extract a substring.', 'text'),
  fn('left', '(text, n)', 'First n characters.', 'text'),
  fn('right', '(text, n)', 'Last n characters.', 'text'),
  fn('position', '(substring IN text)', 'Location of substring.', 'integer'),
  fn('strpos', '(text, substring)', 'Location of substring.', 'integer'),
  fn('replace', '(text, from, to)', 'Replace all occurrences of from with to.', 'text'),
  fn('concat', '(value [, …])', 'Concatenate arguments, ignoring nulls.', 'text'),
  fn('concat_ws', '(separator, value [, …])', 'Concatenate with a separator, ignoring nulls.', 'text'),
  fn('format', '(formatstr [, arg …])', 'Format arguments like sprintf.', 'text'),
  fn('lpad', '(text, length [, fill])', 'Pad on the left.', 'text'),
  fn('rpad', '(text, length [, fill])', 'Pad on the right.', 'text'),
  fn('repeat', '(text, n)', 'Repeat text n times.', 'text'),
  fn('reverse', '(text)', 'Reverse characters.', 'text'),
  fn('split_part', '(text, delimiter, n)', 'n-th field after splitting on delimiter.', 'text'),
  fn('string_to_array', '(text, delimiter [, null_string])', 'Split into an array.', 'text[]'),
  fn('regexp_replace', '(text, pattern, replacement [, flags])', 'Replace regex matches.', 'text'),
  fn('regexp_matches', '(text, pattern [, flags])', 'Regex captures as a set of arrays.', 'setof text[]'),
  fn('regexp_split_to_table', '(text, pattern [, flags])', 'Split into rows on a regex.', 'setof text'),
  fn('md5', '(text)', 'MD5 hash as hex.', 'text'),
  fn('to_char', '(value, format)', 'Format a date/number as text.', 'text'),
  fn('to_number', '(text, format)', 'Parse a number.', 'numeric'),
  fn('to_date', '(text, format)', 'Parse a date.', 'date'),
  fn('to_timestamp', '(text, format) | (epoch)', 'Parse a timestamp.', 'timestamptz'),
  fn('quote_ident', '(text)', 'Quote as an identifier when needed.', 'text'),
  fn('quote_literal', '(text)', 'Quote as a string literal.', 'text'),
  // dates
  fn('now', '()', 'Current date and time (start of transaction).', 'timestamptz'),
  fn('clock_timestamp', '()', 'Current date and time (changes during statement).', 'timestamptz'),
  fn('date_trunc', "(field, source [, time_zone])", "Truncate to the given precision ('day', 'month'…).", 'timestamp'),
  fn('date_part', '(field, source)', 'Subfield of a date/time value.', 'double precision'),
  fn('extract', '(field FROM source)', 'Subfield of a date/time value.', 'numeric'),
  fn('age', '(timestamp [, timestamp])', 'Interval between timestamps.', 'interval'),
  fn('make_date', '(year, month, day)', 'Build a date.', 'date'),
  fn('make_interval', '(years, months, weeks, days, hours, mins, secs)', 'Build an interval.', 'interval'),
  fn('generate_series', '(start, stop [, step])', 'Set of values from start to stop.', 'setof'),
  // math
  fn('abs', '(x)', 'Absolute value.'),
  fn('round', '(x [, digits])', 'Round to nearest (or to digits decimals).'),
  fn('ceil', '(x)', 'Smallest integer ≥ x.'),
  fn('floor', '(x)', 'Largest integer ≤ x.'),
  fn('trunc', '(x [, digits])', 'Truncate toward zero.'),
  fn('mod', '(y, x)', 'Remainder of y/x.'),
  fn('power', '(a, b)', 'a raised to the power b.'),
  fn('sqrt', '(x)', 'Square root.'),
  fn('random', '()', 'Random value in [0, 1).', 'double precision'),
  // json
  fn('to_json', '(value)', 'Convert to JSON.', 'json'),
  fn('to_jsonb', '(value)', 'Convert to JSONB.', 'jsonb'),
  fn('json_build_object', '(key, value [, …])', 'Build a JSON object.', 'json'),
  fn('jsonb_build_object', '(key, value [, …])', 'Build a JSONB object.', 'jsonb'),
  fn('json_build_array', '(value [, …])', 'Build a JSON array.', 'json'),
  fn('jsonb_build_array', '(value [, …])', 'Build a JSONB array.', 'jsonb'),
  fn('jsonb_set', '(target, path, new_value [, create_missing])', 'Replace a value at path.', 'jsonb'),
  fn('jsonb_array_elements', '(jsonb)', 'Expand an array into rows.', 'setof jsonb'),
  fn('jsonb_each', '(jsonb)', 'Expand an object into key/value rows.', 'setof record'),
  fn('jsonb_typeof', '(jsonb)', 'Type of the outermost value.', 'text'),
  fn('jsonb_pretty', '(jsonb)', 'Indented JSON text.', 'text'),
  fn('json_extract_path_text', '(json, path …)', 'Value at path as text.', 'text'),
  // arrays
  fn('array_length', '(array, dimension)', 'Length of the given dimension.', 'integer'),
  fn('cardinality', '(array)', 'Total number of elements.', 'integer'),
  fn('array_append', '(array, element)', 'Append an element.', 'anyarray'),
  fn('array_remove', '(array, element)', 'Remove all occurrences.', 'anyarray'),
  fn('array_position', '(array, element)', 'Index of the first occurrence.', 'integer'),
  fn('array_to_string', '(array, delimiter [, null_string])', 'Join elements as text.', 'text'),
  fn('unnest', '(array)', 'Expand an array into rows.', 'setof'),
  // misc
  fn('gen_random_uuid', '()', 'Random version 4 UUID.', 'uuid'),
  fn('current_setting', '(name [, missing_ok])', 'Current value of a setting.', 'text'),
  fn('set_config', '(name, value, is_local)', 'Set a configuration parameter.', 'text'),
  fn('pg_size_pretty', '(bigint)', 'Human-readable size.', 'text'),
  fn('pg_total_relation_size', '(regclass)', 'Total disk space of a table incl. indexes and TOAST.', 'bigint'),
  fn('pg_relation_size', '(regclass)', 'Disk space of a relation.', 'bigint'),
  fn('pg_database_size', '(name)', 'Disk space of a database.', 'bigint'),
  fn('pg_cancel_backend', '(pid)', 'Cancel the current query of a backend.', 'boolean'),
  fn('pg_terminate_backend', '(pid)', 'Terminate a backend.', 'boolean'),
  fn('pg_sleep', '(seconds)', 'Sleep for the given number of seconds.', 'void'),
  fn('version', '()', 'Server version string.', 'text'),
  fn('nextval', '(regclass)', 'Advance a sequence and return the new value.', 'bigint'),
  fn('currval', '(regclass)', 'Value most recently obtained by nextval.', 'bigint'),
  fn('setval', '(regclass, value [, is_called])', 'Set a sequence value.', 'bigint'),
]

const MSSQL_FUNCTIONS: BuiltinFunction[] = [
  // aggregates
  fn('COUNT', '(expr | *)', 'Number of items in a group.', 'int'),
  fn('COUNT_BIG', '(expr | *)', 'Number of items in a group.', 'bigint'),
  fn('SUM', '(expr)', 'Sum of values.'),
  fn('AVG', '(expr)', 'Average of values.'),
  fn('MIN', '(expr)', 'Minimum value.'),
  fn('MAX', '(expr)', 'Maximum value.'),
  fn('STRING_AGG', '(expr, separator) [WITHIN GROUP (ORDER BY …)]', 'Concatenate values with a separator.', 'nvarchar'),
  fn('STDEV', '(expr)', 'Statistical standard deviation.', 'float'),
  fn('VAR', '(expr)', 'Statistical variance.', 'float'),
  fn('GROUPING', '(column)', 'Whether a column is aggregated in GROUP BY ROLLUP/CUBE.', 'tinyint'),
  // window
  fn('ROW_NUMBER', '() OVER (…)', 'Sequential number of a row within its partition.', 'bigint'),
  fn('RANK', '() OVER (…)', 'Rank with gaps.', 'bigint'),
  fn('DENSE_RANK', '() OVER (…)', 'Rank without gaps.', 'bigint'),
  fn('NTILE', '(n) OVER (…)', 'Group number from 1 to n.', 'bigint'),
  fn('LAG', '(expr [, offset [, default]]) OVER (…)', 'Value from a previous row.'),
  fn('LEAD', '(expr [, offset [, default]]) OVER (…)', 'Value from a following row.'),
  fn('FIRST_VALUE', '(expr) OVER (…)', 'First value in the window frame.'),
  fn('LAST_VALUE', '(expr) OVER (…)', 'Last value in the window frame.'),
  // conditional / conversion
  fn('ISNULL', '(check_expr, replacement)', 'Replace NULL with the replacement value.'),
  fn('COALESCE', '(expr [, …])', 'First non-null argument.'),
  fn('NULLIF', '(expr1, expr2)', 'NULL if both arguments are equal.'),
  fn('IIF', '(condition, true_value, false_value)', 'Inline conditional.'),
  fn('CHOOSE', '(index, value1, value2 [, …])', 'Item at the given 1-based index.'),
  fn('CAST', '(expr AS type)', 'Convert to a data type.'),
  fn('CONVERT', '(type, expr [, style])', 'Convert to a data type with an optional style.'),
  fn('TRY_CAST', '(expr AS type)', 'Convert, or NULL on failure.'),
  fn('TRY_CONVERT', '(type, expr [, style])', 'Convert, or NULL on failure.'),
  fn('TRY_PARSE', '(string AS type [USING culture])', 'Parse, or NULL on failure.'),
  // strings
  fn('LEN', '(string)', 'Number of characters (trailing spaces excluded).', 'int'),
  fn('DATALENGTH', '(expr)', 'Number of bytes.', 'int'),
  fn('LOWER', '(string)', 'Convert to lower case.'),
  fn('UPPER', '(string)', 'Convert to upper case.'),
  fn('LTRIM', '(string)', 'Remove leading spaces.'),
  fn('RTRIM', '(string)', 'Remove trailing spaces.'),
  fn('TRIM', '([chars FROM] string)', 'Remove characters from both ends.'),
  fn('SUBSTRING', '(expr, start, length)', 'Part of a string.'),
  fn('LEFT', '(string, n)', 'Leftmost n characters.'),
  fn('RIGHT', '(string, n)', 'Rightmost n characters.'),
  fn('CHARINDEX', '(substring, string [, start])', 'Position of a substring.', 'int'),
  fn('PATINDEX', "('%pattern%', string)", 'Position of a pattern.', 'int'),
  fn('REPLACE', '(string, pattern, replacement)', 'Replace all occurrences.'),
  fn('REPLICATE', '(string, n)', 'Repeat a string n times.'),
  fn('REVERSE', '(string)', 'Reverse a string.'),
  fn('STUFF', '(string, start, length, insert)', 'Delete a range and insert a string.'),
  fn('CONCAT', '(value, value [, …])', 'Concatenate values, NULLs as empty.'),
  fn('CONCAT_WS', '(separator, value, value [, …])', 'Concatenate with a separator.'),
  fn('FORMAT', '(value, format [, culture])', 'Format a value with a .NET format string.', 'nvarchar'),
  fn('STRING_SPLIT', '(string, separator [, enable_ordinal])', 'Split into rows.', 'table'),
  fn('QUOTENAME', "(string [, quote_char])", 'Delimited identifier.', 'nvarchar'),
  fn('TRANSLATE', '(string, characters, translations)', 'Replace characters one by one.'),
  // dates
  fn('GETDATE', '()', 'Current date and time.', 'datetime'),
  fn('GETUTCDATE', '()', 'Current UTC date and time.', 'datetime'),
  fn('SYSDATETIME', '()', 'Current date and time (high precision).', 'datetime2'),
  fn('SYSUTCDATETIME', '()', 'Current UTC date and time (high precision).', 'datetime2'),
  fn('SYSDATETIMEOFFSET', '()', 'Current date, time and offset.', 'datetimeoffset'),
  fn('DATEADD', '(datepart, number, date)', 'Add an interval to a date.'),
  fn('DATEDIFF', '(datepart, startdate, enddate)', 'Number of datepart boundaries crossed.', 'int'),
  fn('DATEDIFF_BIG', '(datepart, startdate, enddate)', 'Number of datepart boundaries crossed.', 'bigint'),
  fn('DATEPART', '(datepart, date)', 'Integer part of a date.', 'int'),
  fn('DATENAME', '(datepart, date)', 'Name of a date part.', 'nvarchar'),
  fn('DATEFROMPARTS', '(year, month, day)', 'Build a date.', 'date'),
  fn('DATETRUNC', '(datepart, date)', 'Truncate to the given precision.'),
  fn('EOMONTH', '(date [, months])', 'Last day of the month.', 'date'),
  fn('YEAR', '(date)', 'Year of a date.', 'int'),
  fn('MONTH', '(date)', 'Month of a date.', 'int'),
  fn('DAY', '(date)', 'Day of a date.', 'int'),
  fn('ISDATE', '(expr)', '1 if the expression is a valid date.', 'int'),
  // math
  fn('ABS', '(x)', 'Absolute value.'),
  fn('ROUND', '(x, length [, function])', 'Round to the given length.'),
  fn('CEILING', '(x)', 'Smallest integer ≥ x.'),
  fn('FLOOR', '(x)', 'Largest integer ≤ x.'),
  fn('POWER', '(x, y)', 'x raised to the power y.'),
  fn('SQRT', '(x)', 'Square root.', 'float'),
  fn('RAND', '([seed])', 'Random float in [0, 1).', 'float'),
  fn('ISNUMERIC', '(expr)', '1 if the expression is numeric.', 'int'),
  // json
  fn('JSON_VALUE', '(expr, path)', 'Scalar value from JSON text.', 'nvarchar'),
  fn('JSON_QUERY', '(expr [, path])', 'Object or array from JSON text.', 'nvarchar'),
  fn('JSON_MODIFY', '(expr, path, new_value)', 'Update a value in JSON text.', 'nvarchar'),
  fn('ISJSON', '(expr)', '1 if the string is valid JSON.', 'int'),
  fn('OPENJSON', '(json [, path])', 'Rows from JSON text.', 'table'),
  // metadata / system
  fn('NEWID', '()', 'New uniqueidentifier.', 'uniqueidentifier'),
  fn('NEWSEQUENTIALID', '()', 'Sequential GUID (column defaults only).', 'uniqueidentifier'),
  fn('OBJECT_ID', "(name [, type])", 'Object id of a schema-scoped object.', 'int'),
  fn('OBJECT_NAME', '(object_id [, database_id])', 'Name of an object.', 'sysname'),
  fn('SCHEMA_NAME', '([schema_id])', 'Schema name.', 'sysname'),
  fn('DB_NAME', '([database_id])', 'Database name.', 'nvarchar'),
  fn('DB_ID', "([database_name])", 'Database id.', 'int'),
  fn('SUSER_SNAME', '([sid])', 'Login name.', 'nvarchar'),
  fn('USER_NAME', '([id])', 'Database user name.', 'nvarchar'),
  fn('SCOPE_IDENTITY', '()', 'Last identity value inserted in the current scope.', 'numeric'),
  fn('IDENT_CURRENT', "('table')", 'Last identity value generated for a table.', 'numeric'),
  fn('ERROR_MESSAGE', '()', 'Message of the error that caused CATCH to run.', 'nvarchar'),
  fn('ERROR_NUMBER', '()', 'Number of the error that caused CATCH to run.', 'int'),
  fn('ERROR_LINE', '()', 'Line of the error that caused CATCH to run.', 'int'),
  fn('ERROR_SEVERITY', '()', 'Severity of the error that caused CATCH to run.', 'int'),
  fn('XACT_STATE', '()', 'Transaction state of the session.', 'smallint'),
  fn('HASHBYTES', "('algorithm', input)", 'Hash of the input.', 'varbinary'),
]

export const BUILTIN_FUNCTIONS: Record<Dialect, BuiltinFunction[]> = {
  postgres: POSTGRES_FUNCTIONS,
  mssql: MSSQL_FUNCTIONS,
}
