// Keyword and data-type vocabularies used by autocompletion, per dialect.
import type { Dialect } from '@shared/types'

const words = (text: string): string[] => [...new Set(text.trim().split(/\s+/))]

const POSTGRES_KEYWORDS = words(`
  ABORT ABSOLUTE ACCESS ACTION ADD ADMIN AFTER AGGREGATE ALL ALSO ALTER ALWAYS ANALYSE ANALYZE AND ANY ARRAY AS ASC
  ASENSITIVE ASSERTION ASSIGNMENT ASYMMETRIC AT ATOMIC ATTACH ATTRIBUTE AUTHORIZATION BACKWARD BEFORE BEGIN BETWEEN
  BINARY BOTH BREADTH BY CACHE CALL CALLED CASCADE CASCADED CASE CAST CATALOG CHAIN CHARACTERISTICS CHECK CHECKPOINT
  CLASS CLOSE CLUSTER COALESCE COLLATE COLLATION COLUMN COLUMNS COMMENT COMMENTS COMMIT COMMITTED COMPRESSION
  CONCURRENTLY CONFIGURATION CONFLICT CONNECTION CONSTRAINT CONSTRAINTS CONTENT CONTINUE CONVERSION COPY COST CREATE
  CROSS CSV CUBE CURRENT CURRENT_CATALOG CURRENT_DATE CURRENT_ROLE CURRENT_SCHEMA CURRENT_TIME CURRENT_TIMESTAMP
  CURRENT_USER CURSOR CYCLE DATA DATABASE DAY DEALLOCATE DECLARE DEFAULT DEFAULTS DEFERRABLE DEFERRED DEFINER DELETE
  DELIMITER DELIMITERS DEPENDS DEPTH DESC DETACH DICTIONARY DISABLE DISCARD DISTINCT DO DOCUMENT DOMAIN DROP EACH ELSE
  ENABLE ENCODING ENCRYPTED END ENUM ESCAPE EVENT EXCEPT EXCLUDE EXCLUDING EXCLUSIVE EXECUTE EXISTS EXPLAIN EXPRESSION
  EXTENSION EXTERNAL EXTRACT FALSE FAMILY FETCH FILTER FINALIZE FIRST FOLLOWING FOR FORCE FOREIGN FORMAT FORWARD FREEZE
  FROM FULL FUNCTION FUNCTIONS GENERATED GLOBAL GRANT GRANTED GREATEST GROUP GROUPING GROUPS HANDLER HAVING HEADER HOLD
  HOUR IDENTITY IF ILIKE IMMEDIATE IMMUTABLE IMPLICIT IMPORT IN INCLUDE INCLUDING INCREMENT INDEX INDEXES INHERIT
  INHERITS INITIALLY INLINE INNER INOUT INPUT INSENSITIVE INSERT INSTEAD INTERSECT INTERVAL INTO INVOKER IS ISNULL
  ISOLATION JOIN JSON KEY KEYS LABEL LANGUAGE LARGE LAST LATERAL LEADING LEAKPROOF LEAST LEFT LEVEL LIKE LIMIT LISTEN
  LOAD LOCAL LOCALTIME LOCALTIMESTAMP LOCATION LOCK LOCKED LOGGED MAPPING MATCH MATCHED MATERIALIZED MAXVALUE MERGE
  METHOD MINUTE MINVALUE MODE MONTH MOVE NAME NAMES NATURAL NEW NEXT NFC NFD NO NONE NORMALIZE NOT NOTHING NOTIFY
  NOTNULL NOWAIT NULL NULLIF NULLS OBJECT OF OFF OFFSET OIDS OLD ON ONLY OPERATOR OPTION OPTIONS OR ORDER ORDINALITY
  OTHERS OUT OUTER OVER OVERLAPS OVERLAY OVERRIDING OWNED OWNER PARALLEL PARAMETER PARSER PARTIAL PARTITION PASSING
  PASSWORD PLACING PLANS POLICY PRECEDING PREPARE PREPARED PRESERVE PRIMARY PRIOR PRIVILEGES PROCEDURAL PROCEDURE
  PROCEDURES PROGRAM PUBLICATION QUOTE RANGE READ REASSIGN RECURSIVE REF REFERENCES REFERENCING REFRESH REINDEX RELATIVE
  RELEASE RENAME REPEATABLE REPLACE REPLICA RESET RESTART RESTRICT RETURN RETURNING RETURNS REVOKE RIGHT ROLE ROLLBACK
  ROLLUP ROUTINE ROUTINES ROW ROWS RULE SAVEPOINT SCHEMA SCHEMAS SCROLL SEARCH SECOND SECURITY SELECT SEQUENCE SEQUENCES
  SERIALIZABLE SERVER SESSION SESSION_USER SET SETOF SETS SHARE SHOW SIMILAR SIMPLE SKIP SNAPSHOT SOME SQL STABLE
  STANDALONE START STATEMENT STATISTICS STDIN STDOUT STORAGE STORED STRICT STRIP SUBSCRIPTION SUBSTRING SUPPORT SYMMETRIC
  SYSID SYSTEM SYSTEM_USER TABLE TABLES TABLESAMPLE TABLESPACE TEMP TEMPLATE TEMPORARY TEXT THEN TIES TO TRAILING
  TRANSACTION TRANSFORM TREAT TRIGGER TRIM TRUE TRUNCATE TRUSTED TYPE TYPES UESCAPE UNBOUNDED UNCOMMITTED UNENCRYPTED
  UNION UNIQUE UNKNOWN UNLISTEN UNLOGGED UNTIL UPDATE USER USING VACUUM VALID VALIDATE VALIDATOR VALUE VALUES VARIADIC
  VERBOSE VERSION VIEW VIEWS VOLATILE WHEN WHERE WHITESPACE WINDOW WITH WITHIN WITHOUT WORK WRAPPER WRITE XML YEAR YES
  ZONE
`)

const MSSQL_KEYWORDS = words(`
  ADD ALL ALTER AND ANY APPLY AS ASC AUTHORIZATION BACKUP BEGIN BETWEEN BREAK BROWSE BULK BY CASCADE CASE CATCH CHECK
  CHECKPOINT CLOSE CLUSTERED COALESCE COLLATE COLUMN COMMIT COMMITTED COMPUTE CONSTRAINT CONTAINS CONTAINSTABLE CONTINUE
  CONVERT CREATE CROSS CURRENT CURRENT_DATE CURRENT_TIME CURRENT_TIMESTAMP CURRENT_USER CURSOR DATABASE DBCC DEALLOCATE
  DECLARE DEFAULT DELAY DELETE DENY DESC DISK DISTINCT DISTRIBUTED DOUBLE DROP DUMP ELSE ENABLE DISABLE END ERRLVL
  ESCAPE EXCEPT EXEC EXECUTE EXISTS EXIT EXTERNAL FETCH FILE FILLFACTOR FIRST FOR FOREIGN FREETEXT FREETEXTTABLE FROM
  FULL FUNCTION GO GOTO GRANT GROUP HAVING HOLDLOCK IDENTITY IDENTITY_INSERT IDENTITYCOL IF IN INCLUDE INDEX INNER INSERT
  INTERSECT INTO IS ISOLATION JOIN KEY KILL LAST LEFT LEVEL LIKE LINENO LOAD LOGIN MATCHED MERGE NATIONAL NEXT NOCHECK
  NOCOUNT NOLOCK NONCLUSTERED NOT NOWAIT NULL NULLIF OF OFF OFFSET OFFSETS ON ONLY OPEN OPENDATASOURCE OPENQUERY
  OPENROWSET OPENXML OPTION OR ORDER OUT OUTER OUTPUT OVER PARTITION PERCENT PERSISTED PIVOT PLAN PRECISION PRIMARY PRINT
  PROC PROCEDURE PUBLIC RAISERROR RANGE READ READCOMMITTED READONLY READPAST READTEXT READUNCOMMITTED RECONFIGURE RECOMPILE
  REFERENCES REPEATABLE REPLICATION RESTORE RESTRICT RETURN RETURNS REVERT REVOKE RIGHT ROLE ROLLBACK ROWCOUNT ROWGUIDCOL
  ROWLOCK ROWS RULE SAVE SCHEMA SCHEMABINDING SECURITYAUDIT SELECT SEMANTICKEYPHRASETABLE SEMANTICSIMILARITYDETAILSTABLE
  SEMANTICSIMILARITYTABLE SEQUENCE SERIALIZABLE SESSION_USER SET SETUSER SHUTDOWN SNAPSHOT SOME SOURCE STATISTICS
  SYNONYM SYSTEM_USER TABLE TABLESAMPLE TABLOCK TABLOCKX TARGET TEXTSIZE THEN THROW TIES TO TOP TRAN TRANSACTION TRIGGER
  TRUNCATE TRY TRY_CONVERT TSEQUAL TYPE UNCOMMITTED UNION UNIQUE UNPIVOT UPDATE UPDATETEXT UPDLOCK USE USER VALUES
  VARYING VIEW WAITFOR WHEN WHERE WHILE WITH WITHIN WRITETEXT XACT_ABORT XLOCK ZONE
`)

const POSTGRES_TYPES = words(`
  bigint bigserial bit boolean bool box bytea char character cidr circle date daterange decimal
  float4 float8 inet int int2 int4 int8 int4range int8range integer interval json jsonb line lseg macaddr money name
  numeric numrange oid path point polygon real regclass serial serial2 serial4 serial8 smallint smallserial text time
  timetz timestamp timestamptz tsquery tsrange tstzrange tsvector uuid varchar xml
`).concat(['double precision', 'timestamp with time zone', 'character varying'])

const MSSQL_TYPES = words(`
  bigint binary bit char cursor date datetime datetime2 datetimeoffset decimal float geography geometry hierarchyid image
  int money nchar ntext numeric nvarchar real rowversion smalldatetime smallint smallmoney sql_variant sysname table text
  time timestamp tinyint uniqueidentifier varbinary varchar xml
`)

/** Multi-word phrases offered as single keyword items (ranked after single keywords in their context). */
const POSTGRES_PHRASES = [
  'GROUP BY', 'ORDER BY', 'PARTITION BY', 'LEFT JOIN', 'RIGHT JOIN', 'INNER JOIN', 'FULL JOIN', 'CROSS JOIN', 'LEFT JOIN LATERAL',
  'UNION ALL', 'IS NULL', 'IS NOT NULL', 'IS DISTINCT FROM', 'NOT IN', 'NOT EXISTS', 'INSERT INTO', 'DELETE FROM',
  'CREATE TABLE', 'CREATE INDEX', 'CREATE VIEW', 'CREATE OR REPLACE FUNCTION', 'CREATE OR REPLACE VIEW', 'ALTER TABLE',
  'DROP TABLE', 'ON CONFLICT', 'DO NOTHING', 'DO UPDATE SET', 'NULLS FIRST', 'NULLS LAST', 'PRIMARY KEY', 'FOREIGN KEY',
  'IF EXISTS', 'IF NOT EXISTS', 'EXPLAIN ANALYZE', 'SELECT DISTINCT', 'FOR UPDATE', 'WITH RECURSIVE',
]

const MSSQL_PHRASES = [
  'GROUP BY', 'ORDER BY', 'PARTITION BY', 'LEFT JOIN', 'RIGHT JOIN', 'INNER JOIN', 'FULL JOIN', 'CROSS JOIN', 'CROSS APPLY',
  'OUTER APPLY', 'UNION ALL', 'IS NULL', 'IS NOT NULL', 'NOT IN', 'NOT EXISTS', 'INSERT INTO', 'DELETE FROM', 'CREATE TABLE',
  'CREATE INDEX', 'CREATE VIEW', 'CREATE OR ALTER PROCEDURE', 'CREATE OR ALTER VIEW', 'CREATE OR ALTER FUNCTION',
  'ALTER TABLE', 'DROP TABLE', 'IF EXISTS', 'PRIMARY KEY', 'FOREIGN KEY', 'BEGIN TRANSACTION', 'COMMIT TRANSACTION',
  'ROLLBACK TRANSACTION', 'BEGIN TRY', 'END TRY', 'BEGIN CATCH', 'END CATCH', 'SELECT DISTINCT', 'SELECT TOP',
  'OFFSET FETCH', 'WITH (NOLOCK)', 'SET NOCOUNT ON', 'WHEN MATCHED THEN', 'WHEN NOT MATCHED THEN',
]

/** Keywords that begin a statement (ranked first at the start of a statement). */
const STATEMENT_STARTERS: Record<Dialect, string[]> = {
  postgres: [
    'SELECT', 'WITH', 'INSERT', 'UPDATE', 'DELETE', 'CREATE', 'ALTER', 'DROP', 'TRUNCATE', 'EXPLAIN', 'BEGIN', 'COMMIT',
    'ROLLBACK', 'SET', 'SHOW', 'GRANT', 'REVOKE', 'VACUUM', 'ANALYZE', 'COPY', 'CALL', 'DO', 'MERGE', 'VALUES', 'TABLE',
    'COMMENT', 'REFRESH', 'REINDEX', 'LOCK', 'PREPARE', 'EXECUTE', 'LISTEN', 'NOTIFY', 'DISCARD', 'RESET',
  ],
  mssql: [
    'SELECT', 'WITH', 'INSERT', 'UPDATE', 'DELETE', 'CREATE', 'ALTER', 'DROP', 'TRUNCATE', 'BEGIN', 'COMMIT', 'ROLLBACK',
    'DECLARE', 'SET', 'EXEC', 'EXECUTE', 'USE', 'GO', 'PRINT', 'IF', 'WHILE', 'MERGE', 'GRANT', 'REVOKE', 'DENY', 'RAISERROR',
    'THROW', 'RETURN', 'WAITFOR', 'DBCC', 'BACKUP', 'RESTORE',
  ],
}

/** Keywords that usually follow an expression / relation (ranked first after an identifier). */
const FOLLOWERS: Record<Dialect, string[]> = {
  postgres: [
    'FROM', 'WHERE', 'AS', 'AND', 'OR', 'JOIN', 'LEFT JOIN', 'INNER JOIN', 'ON', 'USING', 'GROUP BY', 'ORDER BY', 'HAVING',
    'LIMIT', 'OFFSET', 'ASC', 'DESC', 'UNION', 'UNION ALL', 'EXCEPT', 'INTERSECT', 'IN', 'NOT', 'LIKE', 'ILIKE', 'BETWEEN',
    'IS NULL', 'IS NOT NULL', 'RETURNING', 'SET', 'VALUES', 'WINDOW', 'FETCH', 'FOR UPDATE', 'NULLS LAST', 'THEN', 'ELSE', 'END',
  ],
  mssql: [
    'FROM', 'WHERE', 'AS', 'AND', 'OR', 'JOIN', 'LEFT JOIN', 'INNER JOIN', 'ON', 'CROSS APPLY', 'OUTER APPLY', 'GROUP BY',
    'ORDER BY', 'HAVING', 'OFFSET', 'ASC', 'DESC', 'UNION', 'UNION ALL', 'EXCEPT', 'INTERSECT', 'IN', 'NOT', 'LIKE',
    'BETWEEN', 'IS NULL', 'IS NOT NULL', 'OUTPUT', 'SET', 'VALUES', 'WITH (NOLOCK)', 'THEN', 'ELSE', 'END', 'OPTION',
  ],
}

export interface DialectVocabulary {
  keywords: string[]
  phrases: string[]
  types: string[]
  statementStarters: string[]
  followers: string[]
}

export const VOCABULARY: Record<Dialect, DialectVocabulary> = {
  postgres: {
    keywords: POSTGRES_KEYWORDS,
    phrases: POSTGRES_PHRASES,
    types: POSTGRES_TYPES,
    statementStarters: STATEMENT_STARTERS.postgres,
    followers: FOLLOWERS.postgres,
  },
  mssql: {
    keywords: MSSQL_KEYWORDS,
    phrases: MSSQL_PHRASES,
    types: MSSQL_TYPES,
    statementStarters: STATEMENT_STARTERS.mssql,
    followers: FOLLOWERS.mssql,
  },
}

const keywordSets: Record<Dialect, ReadonlySet<string>> = {
  postgres: new Set(POSTGRES_KEYWORDS),
  mssql: new Set(MSSQL_KEYWORDS),
}

/** True when the upper-cased word is a keyword of the dialect. */
export function isKeyword(upper: string, dialect: Dialect): boolean {
  return keywordSets[dialect].has(upper)
}
